name: Trigger auto deployment for container-app-6lxi6bv4h6322

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-6lxi6bv4h6322-AutoDeployTrigger-7f602baf-269a-4b84-9bfc-2db7258cbfd5.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPP6LXI6BV4H6322_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPP6LXI6BV4H6322_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPP6LXI6BV4H6322_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPP6LXI6BV4H6322_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPP6LXI6BV4H6322_REGISTRY_PASSWORD }}
          containerAppName: container-app-6lxi6bv4h6322
          resourceGroup: appspacesragapp9da791f2
          imageToBuild: default/container-app-6lxi6bv4h6322:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


